#!/bin/bash
#SBATCH --gres gpu:2
#SBATCH --cpus-per-gpu=2
#SBATCH --mem=16G
#SBATCH  -t 4-00:00:00 
source /share/home/houedry/anaconda3/bin/activate
conda activate base
export OMP_NUM_THREADS=1
mkdir -p /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.0001 -reg 0.0001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 0 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.0001 -reg 0.0001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 1 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.0001 -reg 0.0001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 2 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.0001 -reg 0.0001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 3 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.0001 -reg 0.0001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 4 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.0001 -reg 0.001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 0 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.0001 -reg 0.001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 1 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.0001 -reg 0.001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 2 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.0001 -reg 0.001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 3 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.0001 -reg 0.001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 4 &
wait
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.0001 -reg 0.01 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 0 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.0001 -reg 0.01 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 1 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.0001 -reg 0.01 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 2 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.0001 -reg 0.01 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 3 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.0001 -reg 0.01 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 4 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.0001 -reg 0.1 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 0 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.0001 -reg 0.1 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 1 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.0001 -reg 0.1 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 2 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.0001 -reg 0.1 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 3 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.0001 -reg 0.1 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 4 &
wait
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.0001 -reg 0.5 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 0 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.0001 -reg 0.5 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 1 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.0001 -reg 0.5 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 2 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.0001 -reg 0.5 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 3 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.0001 -reg 0.5 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 4 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.0001 -reg 1.0 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 0 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.0001 -reg 1.0 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 1 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.0001 -reg 1.0 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 2 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.0001 -reg 1.0 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 3 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.0001 -reg 1.0 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 4 &
wait
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.0001 -reg 10 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 0 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.0001 -reg 10 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 1 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.0001 -reg 10 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 2 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.0001 -reg 10 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 3 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.0001 -reg 10 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 4 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.001 -reg 0.0001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 0 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.001 -reg 0.0001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 1 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.001 -reg 0.0001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 2 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.001 -reg 0.0001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 3 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.001 -reg 0.0001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 4 &
wait
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.001 -reg 0.001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 0 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.001 -reg 0.001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 1 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.001 -reg 0.001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 2 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.001 -reg 0.001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 3 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.001 -reg 0.001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 4 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.001 -reg 0.01 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 0 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.001 -reg 0.01 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 1 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.001 -reg 0.01 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 2 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.001 -reg 0.01 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 3 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.001 -reg 0.01 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 4 &
wait
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.001 -reg 0.1 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 0 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.001 -reg 0.1 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 1 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.001 -reg 0.1 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 2 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.001 -reg 0.1 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 3 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.001 -reg 0.1 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 4 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.001 -reg 0.5 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 0 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.001 -reg 0.5 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 1 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.001 -reg 0.5 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 2 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.001 -reg 0.5 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 3 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.001 -reg 0.5 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 4 &
wait
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.001 -reg 1.0 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 0 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.001 -reg 1.0 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 1 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.001 -reg 1.0 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 2 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.001 -reg 1.0 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 3 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.001 -reg 1.0 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 4 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.001 -reg 10 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 0 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.001 -reg 10 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 1 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.001 -reg 10 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 2 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.001 -reg 10 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 3 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.001 -reg 10 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 4 &
wait
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.01 -reg 0.0001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 0 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.01 -reg 0.0001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 1 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.01 -reg 0.0001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 2 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.01 -reg 0.0001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 3 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.01 -reg 0.0001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 4 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.01 -reg 0.001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 0 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.01 -reg 0.001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 1 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.01 -reg 0.001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 2 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.01 -reg 0.001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 3 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.01 -reg 0.001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 4 &
wait
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.01 -reg 0.01 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 0 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.01 -reg 0.01 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 1 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.01 -reg 0.01 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 2 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.01 -reg 0.01 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 3 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.01 -reg 0.01 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 4 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.01 -reg 0.1 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 0 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.01 -reg 0.1 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 1 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.01 -reg 0.1 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 2 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.01 -reg 0.1 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 3 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.01 -reg 0.1 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 4 &
wait
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.01 -reg 0.5 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 0 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.01 -reg 0.5 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 1 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.01 -reg 0.5 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 2 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.01 -reg 0.5 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 3 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.01 -reg 0.5 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 4 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.01 -reg 1.0 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 0 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.01 -reg 1.0 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 1 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.01 -reg 1.0 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 2 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.01 -reg 1.0 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 3 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.01 -reg 1.0 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 4 &
wait
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.01 -reg 10 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 0 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.01 -reg 10 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 1 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.01 -reg 10 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 2 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.01 -reg 10 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 3 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.01 -reg 10 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 4 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.1 -reg 0.0001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 0 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.1 -reg 0.0001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 1 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.1 -reg 0.0001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 2 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.1 -reg 0.0001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 3 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.1 -reg 0.0001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 4 &
wait
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.1 -reg 0.001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 0 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.1 -reg 0.001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 1 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.1 -reg 0.001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 2 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.1 -reg 0.001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 3 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.1 -reg 0.001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 4 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.1 -reg 0.01 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 0 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.1 -reg 0.01 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 1 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.1 -reg 0.01 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 2 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.1 -reg 0.01 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 3 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.1 -reg 0.01 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 4 &
wait
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.1 -reg 0.1 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 0 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.1 -reg 0.1 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 1 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.1 -reg 0.1 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 2 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.1 -reg 0.1 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 3 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.1 -reg 0.1 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 4 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.1 -reg 0.5 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 0 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.1 -reg 0.5 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 1 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.1 -reg 0.5 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 2 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.1 -reg 0.5 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 3 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.1 -reg 0.5 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 4 &
wait
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.1 -reg 1.0 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 0 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.1 -reg 1.0 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 1 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.1 -reg 1.0 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 2 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.1 -reg 1.0 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 3 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.1 -reg 1.0 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 4 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.1 -reg 10 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 0 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.1 -reg 10 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 1 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.1 -reg 10 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 2 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.1 -reg 10 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 3 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.1 -reg 10 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 4 &
wait
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.5 -reg 0.0001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 0 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.5 -reg 0.0001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 1 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.5 -reg 0.0001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 2 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.5 -reg 0.0001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 3 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.5 -reg 0.0001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 4 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.5 -reg 0.001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 0 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.5 -reg 0.001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 1 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.5 -reg 0.001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 2 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.5 -reg 0.001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 3 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.5 -reg 0.001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 4 &
wait
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.5 -reg 0.01 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 0 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.5 -reg 0.01 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 1 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.5 -reg 0.01 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 2 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.5 -reg 0.01 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 3 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.5 -reg 0.01 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 4 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.5 -reg 0.1 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 0 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.5 -reg 0.1 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 1 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.5 -reg 0.1 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 2 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.5 -reg 0.1 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 3 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.5 -reg 0.1 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 4 &
wait
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.5 -reg 0.5 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 0 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.5 -reg 0.5 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 1 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.5 -reg 0.5 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 2 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.5 -reg 0.5 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 3 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.5 -reg 0.5 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 4 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.5 -reg 1.0 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 0 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.5 -reg 1.0 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 1 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.5 -reg 1.0 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 2 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.5 -reg 1.0 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 3 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.5 -reg 1.0 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 4 &
wait
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.5 -reg 10 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 0 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.5 -reg 10 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 1 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.5 -reg 10 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 2 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.5 -reg 10 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 3 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 0.5 -reg 10 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 4 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 1.0 -reg 0.0001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 0 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 1.0 -reg 0.0001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 1 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 1.0 -reg 0.0001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 2 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 1.0 -reg 0.0001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 3 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 1.0 -reg 0.0001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 4 &
wait
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 1.0 -reg 0.001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 0 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 1.0 -reg 0.001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 1 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 1.0 -reg 0.001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 2 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 1.0 -reg 0.001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 3 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 1.0 -reg 0.001 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 4 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 1.0 -reg 0.01 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 0 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 1.0 -reg 0.01 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 1 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 1.0 -reg 0.01 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 2 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 1.0 -reg 0.01 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 3 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 1.0 -reg 0.01 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 4 &
wait
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 1.0 -reg 0.1 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 0 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 1.0 -reg 0.1 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 1 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 1.0 -reg 0.1 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 2 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 1.0 -reg 0.1 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 3 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 1.0 -reg 0.1 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 4 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 1.0 -reg 0.5 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 0 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 1.0 -reg 0.5 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 1 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 1.0 -reg 0.5 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 2 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 1.0 -reg 0.5 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 3 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 1.0 -reg 0.5 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 4 &
wait
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 1.0 -reg 1.0 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 0 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 1.0 -reg 1.0 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 1 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 1.0 -reg 1.0 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 2 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 1.0 -reg 1.0 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 3 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 1.0 -reg 1.0 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 4 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 1.0 -reg 10 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 0 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 1.0 -reg 10 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 1 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 1.0 -reg 10 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 2 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 1.0 -reg 10 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 3 &
python /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/expes/launch_distance_hyperbolicity_learning.py -r /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/results_expes/expe_test/ -dp /share/home/houedry/projects/hyperbolic/DifferentiableHyperbolicity/hyperbolicity/datasets/ -ds celegan -lr 1.0 -reg 10 -ssp 10000 -ssd 10000 -sssm 10000 -ep 500 -bs 32 -rn 4 &
wait
