learning_rates: [0.1]
distance_regs: [ 0.1]
scale_delta: [1.0, 5.0, 10.0, 50.0, 100.0]
epochs: [1000]
batch_size: [[32,100], [40,100], [16,100], [8,100], [24,100]]
dataset: '/share/home/houedry/projects/DifferentiableHyperbolicity/hyperbolicity/datasets/D_celegan.pkl'

