learning_rates: [0.1, 0.01, 0.001]
distance_regs: [0.1, 0.01, 1.0]
scale_delta: [0.01, 0.1, 1.0, 10.0]
epochs: [1000]
batch_size: [[32,100]]
dataset: '/share/home/houedry/projects/DifferentiableHyperbolicity/hyperbolicity/datasets/D_zeisel.pkl'

