learning_rates: [0.01]
distance_regs: [0.001]
scale_delta: [0.001]
epochs: [1000]
batch_size: [[32,100]]
dataset: '/share/home/houedry/projects/DifferentiableHyperbolicity/hyperbolicity/datasets/D_cbmc.pkl'

